services:
  promtail:
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/HC_Volume_104655540/docker/containers:/var/lib/docker/containers:ro
      - /opt/planerix/infra/observability/promtail/promtail.yml:/etc/promtail/promtail.yml:ro
      - promtail-positions:/var/lib/promtail

volumes:
  promtail-positions:
