global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["planerix-prometheus:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["planerix-node-exporter:9100"]
